

mqtt-broker:
  basic:
    host: 127.0.0.1
    port: 1881
  acl:
    host: 127.0.0.1
    port: 1882
  test:
    #    #Thanos
    #    host: mqtt-thanos.test.com.cn
    #    port: 8883
    #    enableTLS: true
    # local
    host: 127.0.0.1
    port: 1883
    enableTLS: false

logging:
  level:
    ROOT: info
    com.test: debug

device:
  v1:
    proofUserName: "V1/PROOF"
    # UP/{dsn}
    publishTopic: "UP/{}"
    # DOWN/{dsn}
    subscribeTopicFilter: "DOWN/{}"

dnc:
  user: testCloud
  subscribe:
    v1TopicFilter: "$share/dnc/UP/+"
    v2TopicFilter: "$share/dnc/V2/UP/+"
    v3TopicFilter: "$share/dnc/V3/UP/+"
    v3ProofTopicFilter: "$share/dnc/V3/UP/PROOF/+"
    v3IfpTopicFilter: "$share/dnc/V3/UP/IFP/+"
    v3OBTopicFilter: "$share/dnc/V3/UP/OB/+"
    testTopicFilter: "$share/dnc/TEST/UP/+"
    qos: 1
  publish:
    v1TopicPrefix: "DOWN/"
    v2TopicPrefix: "V2/DOWN/"
    v3TopicPrefix: "V3/DOWN/"
    v3ProofTopicPrefix: "V3/DOWN/PROOF/"
    v3IfpTopicPrefix: "V3/DOWN/IFP/"
    v3OBTopicPrefix: "V3/DOWN/OB/"
    testTopicPrefix: "TEST/DOWN/"
    qos: 1
    responseMessageExpirySeconds: 60
  v3:
    max-payload-size: 64
    onboard:
      max_retry: 3
      connect-ttl: 10
      kick-out-after-finish-delay-seconds: 10 # ob-finish-kick-out-delay-seconds
    partial-message:
      send-orr-delay-second: 10
      send-error-after-orr-delay-seconds: 10
      kick-out-after-orr-error-delay-seconds: 3
      schedule-pool-size: 9
